/*
 *                        AT&T - PROPRIETARY
 *          THIS FILE CONTAINS PROPRIETARY INFORMATION OF
 *        AT&T AND IS NOT TO BE DISCLOSED OR USED EXCEPT IN
 *             ACCORDANCE WITH APPLICABLE AGREEMENTS.
 *
 *          Copyright (c) 2014 AT&T Knowledge Ventures
 *              Unpublished and Not for Publication
 *                     All Rights Reserved
 */
package com.att.research.xacml.admin.view.windows;

import oasis.names.tc.xacml._3_0.core.schema.wd_17.ApplyType;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.event.ShortcutAction.KeyCode;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class ExpressionSelectionWindow extends Window {

	public static String	OPTION_APPLY = "Apply";
	public static String	OPTION_VALUE = "Attribute Value";
	public static String	OPTION_DESIGNATOR = "Attribute Designator";
	public static String	OPTION_SELECTOR = "Attribute Selector";
	public static String	OPTION_VARIABLE = "Variable Reference";
	
	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Button buttonSave;
	@AutoGenerated
	private OptionGroup optionGroupExpression;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private final ExpressionSelectionWindow self = this;
	boolean isSaved = false;
	String selection = null;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 * @param parentApply 
	 */
	public ExpressionSelectionWindow(ApplyType parentApply, boolean isAttributeAssignment, boolean mustBeBag, boolean mustBeValue) {
		buildMainLayout();
		//setCompositionRoot(mainLayout);
		setContent(mainLayout);
		//
		// Set our shortcuts
		//
		this.setCloseShortcut(KeyCode.ESCAPE);
		//
		// Finish GUI initialization
		//
		this.initializeOption(parentApply, isAttributeAssignment, mustBeBag, mustBeValue);
		this.initializeButtons();
	}
	
	private void initializeOption(ApplyType parentApply, boolean isAttributeAssignment, boolean mustBeBag, boolean mustBeValue) {
//		if (!isAttributeAssignment) {
			this.optionGroupExpression.addItem(OPTION_APPLY);
//		}
		if (!mustBeBag || mustBeValue) {
			this.optionGroupExpression.addItem(OPTION_VALUE);
		}
		if (mustBeBag || !mustBeValue) {
			this.optionGroupExpression.addItem(OPTION_DESIGNATOR);
			this.optionGroupExpression.addItem(OPTION_SELECTOR);
		}
		this.optionGroupExpression.addItem(OPTION_VARIABLE);
		//
		// Default Selection
		//
		if (!isAttributeAssignment) {
			this.optionGroupExpression.select(OPTION_APPLY);
		} else {
			if (!mustBeBag || mustBeValue) {
				this.optionGroupExpression.select(OPTION_VALUE);
			} else {
				this.optionGroupExpression.select(OPTION_DESIGNATOR);
			}
		}
	}
	
	private void initializeButtons() {
		this.buttonSave.addClickListener(new ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				self.isSaved = true;
				self.selection = self.optionGroupExpression.getValue().toString();
				self.close();
			}			
		});
	}
	
	public String	getSelection() {
		if (this.isSaved == false) {
			return null;
		}
		return this.selection;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");
		
		// optionGroupExpression
		optionGroupExpression = new OptionGroup();
		optionGroupExpression
				.setCaption("Select One Of The Following Types of Expressions");
		optionGroupExpression.setImmediate(false);
		optionGroupExpression.setWidth("-1px");
		optionGroupExpression.setHeight("-1px");
		mainLayout.addComponent(optionGroupExpression);
		
		// buttonSave
		buttonSave = new Button();
		buttonSave.setCaption("Select");
		buttonSave.setImmediate(false);
		buttonSave.setWidth("-1px");
		buttonSave.setHeight("-1px");
		mainLayout.addComponent(buttonSave);
		mainLayout.setComponentAlignment(buttonSave, new Alignment(24));
		
		return mainLayout;
	}

}
